# Generated by Django 2.2.2 on 2020-04-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200, null=True)),
                ('salary', models.CharField(max_length=1000, null=True)),
                ('d_o_j', models.DateTimeField(auto_now_add=True, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
